kind: Service
apiVersion: v1
metadata:
  name: ushahidi-client-pipe
spec:
  selector:
    app: ushahidi-client-pipe
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ushahidi-client
  labels:
    app: ushahidi-client-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ushahidi-client-pipe
  template:
    metadata:
      labels:
        app: ushahidi-client-pipe
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ushahidi-client-pipe
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
